server:
  port:
    8290
  servlet:
    context-path: 
              /metrica
logging:
  level:
    org:
      hibernate:
        SQL:
          debug
    root:
      INFO
  file:
    saying-local.log
        
spring:
  datasource:
    url: 
      jdbc:mysql://localhost/db_sayings?useSSL=false&allowPublicKeyRetrieval=true
    username:
      root
    password:
      metrica123
    driver-class-name:
      com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: 
      org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto:
      create-drop      

metrica:
  data:
    # Possible values: dataBase | inMemory
    service:
        inMemory
       

      
      
   
  
    
